 ### Crear un nuevo usuario
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Leonardo Castañeda"
}

###

### Obtener todos los usuarios
GET http://localhost:3000/users
Accept: application/json

###

### Obtener un usuario por ID
GET http://localhost:3000/users/1
Accept: application/json

###

### Actualizar un usuario
PUT http://localhost:3000/users
Content-Type: application/json

{
  "userId": 1,
  "name": "Leonardo C."
}

###

### Eliminar un usuario
DELETE http://localhost:3000/users/1
Accept: application/json

###

### Crear un contacto para un usuario
POST http://localhost:3000/contacts
Content-Type: application/json

{
  "firstName": "Maildita",
  "lastName": "Nerea",
  "email": "maldita.nerea@email.com",
  "phone": "555-9876",
  "isFavorite": false,
  "userId": 1
}

###

### Obtener todos los contactos
GET http://localhost:3000/contacts
Accept: application/json

###

### Obtener un contacto por ID
GET http://localhost:3000/contacts/6
Accept: application/json

###

### Actualizar un contacto
PUT http://localhost:3000/contacts/1
Content-Type: application/json

{
  "firstName": "Carlos",
  "lastName": "Gomez Arana",
  "email": "carlos.gomezarana@email.com",
  "phone": "555-6543",
  "isFavorite": false,
  "userId": 1
}

###

### Eliminar un contacto
DELETE http://localhost:3000/contacts/6
Accept: application/json

###

### Recuperar un contacto

PATCH http://localhost:3000/contacts/6/recover
Accept: application/json