 ### Crear un nuevo usuario
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Arnau Vida"
}

###

### Obtener todos los usuarios
GET http://localhost:3000/users
Accept: application/json

###

### Obtener un usuario por ID
GET http://localhost:3000/users/6
Accept: application/json

###

### Actualizar un usuario
PUT   http://localhost:3000/users/10
Content-Type: application/json

{
  "userId": 5,
  "name": "juan."
}

###

### Eliminar un usuario
DELETE http://localhost:3000/users/2
Accept: application/json

###

### Crear un contacto para un usuario

POST http://localhost:3000/contacts/
Content-Type: application/json

{
  "firstName": "Maildita",
  "lastName": "Nerea",
  "email": "maldita.nerea@email.com",
  "phone": "555-9876",
  "isFavorite": false,
  "userId": 5
}



###

### Obtener todos los contactos
GET http://localhost:3000/contacts/
Accept: application/json

###

### Obtener un contacto por ID

GET http://localhost:3000/contacts/8
 
###

### Actualizar un contacto

PUT http://localhost:3000/contacts/8
Content-Type: application/json

{
  "firstName": "Carlos Luis",
  "lastName": "Gomez Arana",
  "email": "carlos.gomezarana@email.com",
  "phone": "555-6543",
  "isFavorite": true,
  "userId": 5

}



### Eliminar un contacto

DELETE http://localhost:3000/contacts/8
Accept: application/json

###

### Recuperar un contacto

PATCH http://localhost:3000/contacts/8/recover
Accept: application/json

###

### Marcar un contacto como favorito y al contrario

PATCH http://localhost:3000/contacts/8/favorites

###

### Recuperar un contacto

PATCH http://localhost:3000/contacts/6/recover
Accept: application/json

###

### Marcar un contacto como favorito y al contrario

PATCH http://localhost:3000/contacts/6/favorites
Accept: application/json
